#Node build version
FROM node:16.1.0 as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV REACT_APP_API_URL=https://pav-back.herokuapp.com

COPY package.json .

RUN npm i

COPY . .

RUN npm run build

#Nginx server
FROM nginx:1.16.0-alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE $PORT
 
CMD ["nginx", "-g", "daemon off;"]