export { default as About } from './About'
export { default as Home } from './Home'
export { default as OfferDetails } from './OfferDetails'
export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
export { default as ForgotPassword } from './ForgotPassword'
export { default as Register } from './Register'
