export { default as About } from './About'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as NotFound } from './NotFound'
export { default as Register } from './Register'
export { default as Search } from './Search'
export { default as User } from './User'
